### ISSUE TITLE
Handle server groups information (HA/affinity/anti-affinity)

### ISSUE THREAD

**Issue by kayrus** [sapcc/elektra#370] opened 2018-09-18 12:13 UTC
1) Show a dedicated page where we can list all available server groups and their members
2) on the server page customer should see server group membership when it is available
3) when customer creates a server, he should be able to specify a server group, or even create one when there are no server groups available.

**Comment by edda** [comment] 2018-09-24 11:38
This is a duplicate of #209. Will add your comment to that ticket and close this one.

**Closed by edda** 2018-09-24 11:38 UTC
